### ISSUE TITLE
[feature request] Microsoft Visual Studio Community 2022 

### ISSUE THREAD

**Issue by Tom-Neverwinter** [Venthe/vscode-fauxpilot#13]
feature request to Add compatibility to Microsoft Visual Studio Community 2022

**Comment by Venthe** [comment]
Hello; sorry for the delay. Github hasn't sent me any notifications...

Nevertheless - this was something that I did in a spare hour or so; I do not use Visual Studio on a day-to-day basis, so I will not be able to assist in creating a version for VS unless someone could instruct me how to do so :)
