### ISSUE TITLE
Option to switch to Fauxpilot "python-backend" by making "model" configurable.

### ISSUE THREAD

**Issue by michaelfeil** [Venthe/vscode-fauxpilot#14]
In the newer fauxpilot there is also a "py-model", next to "fastertransformer" backend, which enables deployment on low-resource devices (using int8 / float16 support etc.)

To use it, "py-model" would need to be configurable. 

See in: 
https://github.com/Venthe/vscode-fauxpilot/blob/e35c57f6ec86f1b8536c4c6775247ff68ecb42ac/src/FauxpilotCompletionProvider.ts#L70-L71

this could be changed to:
```ts
return this.openai.createCompletion({
            model: workspace.getConfiguration('fauxpilot').get("model"),
            ....
```

And make it configurable, e.g. here: https://github.com/Venthe/vscode-fauxpilot/blob/546b0a023935bea90a1156a3a2b79bf2b98871d7/package.json#L62-L64

**Comment by Venthe** [comment]
Hello; sorry for the delay. Github hasn't sent me any notifications...

done as of ba9f034 and released as 1.1.0. Thanks!
