### ISSUE TITLE
Codium availability ?

### ISSUE THREAD

**Issue by benoit-cty** [Venthe/vscode-fauxpilot#15]
Thanks for the plug-in !

Why is it not available in [Codium](https://vscodium.com/) extensions but only in VS Code ?

**Comment by benoit-cty** [comment]
It is possible by doing:
```
wget https://github.com/Venthe/vscode-fauxpilot/releases/download/1.0.0/fauxpilot-1.0.0.vsix
codium --install-extension fauxpilot-1.0.0.vsix
```

**Comment by Venthe** [comment]
Frankly, because no one has shown any interest :)

I'll investigate, and if it's as easy as you say, should be up today'ish

**Comment by Venthe** [comment]
It's now available :) https://open-vsx.org/extension/venthe/fauxpilot
