### ISSUE TITLE
Not compatible with vscode 1.64.2

### ISSUE THREAD

**Issue by zhanglistar** [Venthe/vscode-fauxpilot#16]
<img width="251" alt="image" src="https://user-images.githubusercontent.com/985418/227073506-135452ee-34f7-4997-8c11-bcf33ca72263.png">

**Comment by Venthe** [comment]
The earliest version that I've tested this with is 1.70.0. I'll try to find some time to actually test the extension with earlier version; as long as API is available - and API used is really limited - should be up.

**Comment by Venthe** [comment]
Unfortunately, I am unable to perform tests as of now. You can always edit the VSIX (It's a ZIP file) to test it yourself.
