### ISSUE TITLE
Expand the suggestion prompt to include tokens from before the current line

### ISSUE THREAD

**Issue by Venthe** [Venthe/vscode-fauxpilot#4]

**Comment by windspirit95** [comment]
I have modified the textBeforeCursor in my local extension, so it could include the text in all lines before the cursor:

```
const fileTextToCursor = document.getText(new Range(0, 0, position.line, position.character));
```

**Comment by elch10** [comment]
@windspirit95, is it fast when you open large files? Like 1000 lines?

**Comment by Venthe** [comment]
One way to do it is to limit the amount of lines/tokens to X max

**Comment by elch10** [comment]
I think it's better also to add all imports, class/function definitions, if max tokens exceed. Because model will be able to use them in next generations. But I don't know how to do that properly.

**Comment by Venthe** [comment]
@windspirit95 I've used your snippet to add limited lines. It will fail on long lines, but still - better than nothing.

@elch10 I don't believe that I can add imports/class definitions. This model is language agnostic, and as such there is no point for me to parse the code.
