### ISSUE TITLE
Completion is not working if `scheme` is `untitiled`

### ISSUE THREAD

**Issue by elch10** [Venthe/vscode-fauxpilot#8]
https://github.com/Venthe/vscode-fauxpilot/blob/b5d460eadb1e5632fcec5bf737da4bd0bfe37304/src/extension.ts#L13
I have tested behavior of that parameter and if you
- specify `scheme: 'untitled'` the completition works only for new files, that is not saved on disk at this moment
- specify `scheme: 'file'`the completition works only for files, that already saved on the disk.

May be we just remove that parameter as it was in `v0.0.1` ?

**Comment by Venthe** [comment]
@elch10 please check if it's working. That's what you get for following blindly logs without reading documentation `¯\_(ツ)_/¯`

**Comment by elch10** [comment]
Thanks, It's working now! :)

**Comment by Venthe** [comment]
No problem :)
